# Generated by Django 3.2.4 on 2021-06-29 01:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0001_initial'),
        ('Alt', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='ordered_shirt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Alt.shirt'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.userprofile'),
        ),
        migrations.AddField(
            model_name='order',
            name='shirts',
            field=models.ManyToManyField(to='Alt.OrderItem'),
        ),
        migrations.AddField(
            model_name='order',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.userprofile'),
        ),
        migrations.AddField(
            model_name='nonprofit',
            name='atrocity',
            field=models.ManyToManyField(blank=True, related_name='NonProfit', to='Alt.Atrocity'),
        ),
        migrations.AddField(
            model_name='nonprofit',
            name='category',
            field=models.ManyToManyField(to='Alt.Category'),
        ),
        migrations.AddField(
            model_name='nonprofit',
            name='shirtList',
            field=models.ManyToManyField(related_name='NonProfit', to='Alt.Shirt'),
        ),
        migrations.AddField(
            model_name='checkoutaddress',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='atrocityshirt',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Alt.country'),
        ),
        migrations.AddField(
            model_name='atrocity',
            name='category',
            field=models.ManyToManyField(to='Alt.Category'),
        ),
        migrations.AddField(
            model_name='atrocity',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Alt.country'),
        ),
        migrations.AlterUniqueTogether(
            name='rating',
            unique_together={('user', 'shirt')},
        ),
        migrations.AlterIndexTogether(
            name='rating',
            index_together={('user', 'shirt')},
        ),
    ]
