# Generated by Django 3.2.4 on 2021-06-29 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Alt', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nonprofit',
            name='category',
            field=models.ManyToManyField(blank=True, to='Alt.Category'),
        ),
        migrations.AlterField(
            model_name='nonprofit',
            name='shirtList',
            field=models.ManyToManyField(blank=True, related_name='NonProfit', to='Alt.Shirt'),
        ),
    ]
