# Generated by Django 3.2.4 on 2021-06-29 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Alt', '0003_auto_20210629_2226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nonprofit',
            name='category',
            field=models.ManyToManyField(blank=True, related_name='NonProfit', to='Alt.Category'),
        ),
    ]
