# Generated by Django 3.2.4 on 2021-06-30 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Alt', '0004_alter_nonprofit_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atrocity',
            name='category',
            field=models.ManyToManyField(blank=True, null=True, to='Alt.Category'),
        ),
        migrations.AlterField(
            model_name='nonprofit',
            name='category',
            field=models.ManyToManyField(blank=True, null=True, related_name='NonProfit', to='Alt.Category'),
        ),
    ]
