# Generated by Django 3.2.4 on 2021-07-09 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Alt', '0006_auto_20210630_0744'),
    ]

    operations = [
        migrations.AddField(
            model_name='atrocity',
            name='total_balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=3),
        ),
        migrations.AddField(
            model_name='nonprofit',
            name='total_balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=3),
        ),
    ]
