# Generated by Django 3.2.4 on 2021-07-11 03:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Alt', '0007_auto_20210709_0714'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atrocity',
            name='title',
            field=models.CharField(max_length=100),
        ),
        migrations.CreateModel(
            name='NonProfitBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('nonprofit', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Alt.nonprofit')),
            ],
        ),
        migrations.CreateModel(
            name='AtrocityBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('atrocity', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Alt.atrocity')),
            ],
        ),
    ]
