# Generated by Django 3.2.4 on 2021-07-11 03:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Alt', '0008_auto_20210711_0347'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='atrocity',
            name='total_balance',
        ),
        migrations.RemoveField(
            model_name='nonprofit',
            name='total_balance',
        ),
    ]
