# Generated by Django 3.2.4 on 2021-07-11 05:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Alt', '0009_auto_20210711_0352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atrocitybalance',
            name='atrocity',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='balance', to='Alt.atrocity'),
        ),
        migrations.AlterField(
            model_name='nonprofitbalance',
            name='nonprofit',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='balance', to='Alt.nonprofit'),
        ),
    ]
