# Generated by Django 3.2.4 on 2021-07-22 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Alt', '0010_auto_20210711_0501'),
    ]

    operations = [
        migrations.AddField(
            model_name='shirt',
            name='altrue_story',
            field=models.TextField(blank=True, null=True),
        ),
    ]
