# Generated by Django 3.2.4 on 2021-07-28 02:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_altruepoints'),
        ('Alt', '0011_shirt_altrue_story'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='api.userprofile'),
        ),
    ]
