# Generated by Django 3.2.4 on 2021-08-09 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Alt', '0012_alter_order_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='ordered_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
