# Generated by Django 3.2.4 on 2021-08-22 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Alt', '0013_alter_order_ordered_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='shirt',
            name='atrocity_list',
            field=models.ManyToManyField(blank=True, null=True, related_name='shirt', to='Alt.Atrocity'),
        ),
    ]
