# Generated by Django 3.2.4 on 2021-08-30 22:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Alt', '0016_alter_shirt_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nonprofit',
            name='atrocity',
        ),
        migrations.RemoveField(
            model_name='nonprofit',
            name='shirtList',
        ),
    ]
