# Generated by Django 3.2.4 on 2021-08-30 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Alt', '0017_auto_20210830_2236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atrocity',
            name='category',
            field=models.ManyToManyField(blank=True, null=True, related_name='atrocity', to='Alt.Category'),
        ),
    ]
