# Generated by Django 3.2.4 on 2021-08-31 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Alt', '0018_alter_atrocity_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shirt',
            name='featured',
            field=models.BooleanField(default=False),
        ),
    ]
