# Generated by Django 3.2.4 on 2021-08-31 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Alt', '0019_alter_shirt_featured'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atrocity',
            name='featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='nonprofit',
            name='featured',
            field=models.BooleanField(default=False),
        ),
    ]
