# Generated by Django 3.2.4 on 2021-09-18 08:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_rename_followers_userprofile_following'),
        ('Alt', '0020_auto_20210831_0048'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyStore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=75)),
            ],
            options={
                'verbose_name': 'CompanyStore',
                'verbose_name_plural': 'CompanyStores',
            },
        ),
        migrations.CreateModel(
            name='ForProfitCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year_started', models.CharField(blank=True, max_length=4, null=True)),
                ('logo', models.CharField(blank=True, max_length=200, null=True)),
                ('headquarters', models.CharField(blank=True, max_length=50, null=True)),
                ('mission', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('website_address', models.TextField(blank=True, null=True)),
                ('atrocities', models.ManyToManyField(related_name='company', to='Alt.Atrocity')),
                ('contributors', models.ManyToManyField(related_name='forprofitcontributors', to='api.UserProfile')),
                ('locations', models.ManyToManyField(blank=True, null=True, related_name='company', to='Alt.CompanyStore')),
                ('nonprofits', models.ManyToManyField(related_name='company', to='Alt.NonProfit')),
                ('owmer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.userprofile')),
            ],
            options={
                'verbose_name_plural': 'ForProfitCompanies',
            },
        ),
        migrations.CreateModel(
            name='CompanyCoupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coupon_code', models.CharField(blank=True, max_length=10, null=True)),
                ('expiration_date', models.DateField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('coupon_image', models.TextField(blank=True, null=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='coupon', to='Alt.forprofitcompany')),
                ('locations', models.ManyToManyField(related_name='coupon', to='Alt.CompanyStore')),
            ],
            options={
                'verbose_name': 'CompanyCoupon',
                'verbose_name_plural': 'CompanyCoupons',
            },
        ),
    ]
