# Generated by Django 3.2.4 on 2021-09-18 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Alt', '0021_companycoupon_companystore_forprofitcompany'),
    ]

    operations = [
        migrations.AddField(
            model_name='companycoupon',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='forprofitcompany',
            name='categories',
            field=models.ManyToManyField(related_name='company', to='Alt.Category'),
        ),
        migrations.AddField(
            model_name='forprofitcompany',
            name='name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='forprofitcompany',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
