# Generated by Django 3.2.4 on 2021-09-18 09:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Alt', '0023_alter_forprofitcompany_contributors'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companycoupon',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='coupon', to='Alt.forprofitcompany'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='companycoupon',
            name='locations',
            field=models.ManyToManyField(blank=True, null=True, related_name='coupon', to='Alt.CompanyStore'),
        ),
    ]
