# Generated by Django 3.2.4 on 2021-09-18 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Alt', '0024_auto_20210918_0942'),
    ]

    operations = [
        migrations.AddField(
            model_name='companycoupon',
            name='name',
            field=models.CharField(default='Bobo', max_length=30),
            preserve_default=False,
        ),
    ]
