# Generated by Django 3.2.4 on 2021-09-19 00:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Alt', '0025_companycoupon_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyNonProfitRelationship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_level', models.IntegerField(choices=[(10, 'Ten Percent'), (25, 'Twenty Five Percent'), (50, 'Fifty Percent'), (100, 'Full Match')])),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relationship', to='Alt.forprofitcompany')),
                ('nonprofit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relationship', to='Alt.nonprofit')),
            ],
            options={
                'verbose_name': 'CompanyNonProfitRelationship',
                'verbose_name_plural': 'CompanyNonProfitRelationships',
            },
        ),
    ]
