# Generated by Django 3.2.4 on 2021-09-19 00:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Alt', '0026_companynonprofitrelationship'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companynonprofitrelationship',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='npcompanyrelation', to='Alt.forprofitcompany'),
        ),
        migrations.AlterField(
            model_name='companynonprofitrelationship',
            name='nonprofit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='npcompanyrelation', to='Alt.nonprofit'),
        ),
        migrations.CreateModel(
            name='CompanyAtrocityRelationship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_level', models.IntegerField(choices=[(10, 'Ten Percent'), (25, 'Twenty Five Percent'), (50, 'Fifty Percent'), (100, 'Full Match')])),
                ('atrocity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='atrocitycompanyrelation', to='Alt.atrocity')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='atrocitycompanyrelation', to='Alt.forprofitcompany')),
            ],
            options={
                'verbose_name': 'CompanyAtrocityRelationship',
                'verbose_name_plural': 'CompanyAtrocityRelationships',
            },
        ),
    ]
