# Generated by Django 3.2.4 on 2021-09-21 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Alt', '0027_auto_20210919_0005'),
    ]

    operations = [
        migrations.AddField(
            model_name='nonprofitbalance',
            name='last_transaction',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
