# Generated by Django 3.2.7 on 2021-10-10 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Alt', '0031_forprofitcompany_is_featured'),
    ]

    operations = [
        migrations.RenameField(
            model_name='forprofitcompany',
            old_name='owmer',
            new_name='owner',
        ),
    ]
