# Generated by Django 3.2.7 on 2021-10-12 17:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_auto_20211010_0733'),
        ('Alt', '0032_rename_owmer_forprofitcompany_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='nonprofit',
            name='owner',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nonprofit', to='api.userprofile'),
        ),
    ]
