# Generated by Django 3.2.7 on 2021-10-12 22:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Alt', '0033_nonprofit_owner'),
    ]

    operations = [
        migrations.CreateModel(
            name='NonProfitProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('information', models.TextField(blank=True, null=True)),
                ('fundraising_goal', models.IntegerField()),
                ('atrocity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='np_project', to='Alt.atrocity')),
                ('cause', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='np_project', to='Alt.category')),
                ('nonprofit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='np_project', to='Alt.nonprofit')),
            ],
        ),
        migrations.CreateModel(
            name='NonProfitAtrocityRelationShip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('atrocity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nonprofitAtrocityRelationship', to='Alt.atrocity')),
                ('nonprofit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nonprofitatrocityRelationship', to='Alt.nonprofit')),
                ('projects', models.ManyToManyField(related_name='nonprofitAtrocityRelationship', to='Alt.NonProfitProject')),
            ],
        ),
    ]
