# Generated by Django 3.2.7 on 2021-10-15 02:16

from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('Alt', '0035_auto_20211015_0213'),
    ]

    operations = [
        migrations.RenameField(
            model_name='companynonprofitrelationship',
            old_name='donation_limit',
            new_name='funding_limit',
        ),
        migrations.RemoveField(
            model_name='companystore',
            name='location',
        ),
        migrations.AddField(
            model_name='companyatrocityrelationship',
            name='funding_limit',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='companystore',
            name='country',
            field=django_countries.fields.CountryField(default='USA', max_length=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='companystore',
            name='state',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='companystore',
            name='street_address',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='companystore',
            name='zip',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
