# Generated by Django 3.2.7 on 2021-10-15 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_auto_20211015_0231'),
        ('Alt', '0038_alter_checkoutaddress_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='forprofitcompany',
            name='contributors_pending',
            field=models.ManyToManyField(related_name='contributors_pending', to='api.UserProfile'),
        ),
    ]
