# Generated by Django 3.2.7 on 2021-10-17 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Alt', '0039_forprofitcompany_contributors_pending'),
    ]

    operations = [
        migrations.AddField(
            model_name='forprofitcompany',
            name='facebook',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='forprofitcompany',
            name='instagram',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='nonprofit',
            name='facebook',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='nonprofit',
            name='instagram',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
