# Generated by Django 3.2.7 on 2021-10-20 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Alt', '0040_auto_20211017_0800'),
    ]

    operations = [
        migrations.AddField(
            model_name='forprofitcompany',
            name='image',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
