# Generated by Django 3.2.7 on 2021-10-23 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Alt', '0043_alter_companycoupon_coupon_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='forprofitcompany',
            name='coupons_of_company',
            field=models.ManyToManyField(blank=True, related_name='coupons_of_company', to='Alt.CompanyCoupon'),
        ),
    ]
