# Generated by Django 3.2.7 on 2021-10-25 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_alter_link_link'),
        ('Alt', '0044_forprofitcompany_coupons_of_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='nonprofitproject',
            name='followers',
            field=models.ManyToManyField(blank=True, related_name='np_project_followers', to='api.UserProfile'),
        ),
        migrations.AddField(
            model_name='nonprofitproject',
            name='supporters',
            field=models.ManyToManyField(blank=True, related_name='np_project_supporters', to='api.UserProfile'),
        ),
        migrations.AddField(
            model_name='nonprofitproject',
            name='title',
            field=models.CharField(blank=True, max_length=140, null=True),
        ),
    ]
