# Generated by Django 3.2.7 on 2021-10-25 03:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Alt', '0045_auto_20211025_0305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nonprofitproject',
            name='atrocity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='np_project', to='Alt.atrocity'),
        ),
    ]
