# Generated by Django 3.2.7 on 2021-10-25 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Alt', '0047_auto_20211025_0316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forprofitcompany',
            name='atrocities',
            field=models.ManyToManyField(blank=True, related_name='company_atrocity', to='Alt.Atrocity'),
        ),
        migrations.AlterField(
            model_name='forprofitcompany',
            name='nonprofits',
            field=models.ManyToManyField(blank=True, related_name='company_nonprofit', to='Alt.NonProfit'),
        ),
    ]
