# Generated by Django 3.2.7 on 2021-10-26 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_link_title'),
        ('Alt', '0049_auto_20211025_0328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nonprofit',
            name='contributors',
            field=models.ManyToManyField(blank=True, related_name='contributors', to='api.UserProfile'),
        ),
        migrations.AlterField(
            model_name='nonprofit',
            name='logo',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='nonprofit',
            name='main_image',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
