# Generated by Django 3.2.7 on 2021-10-26 08:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_link_title'),
        ('Alt', '0050_auto_20211026_0230'),
    ]

    operations = [
        migrations.CreateModel(
            name='AltrueAction',
            fields=[
                ('id', models.IntegerField(auto_created=True, editable=False, primary_key=True, serialize=False)),
                ('requirement', models.TextField()),
                ('points_awarded', models.IntegerField()),
                ('number_of_occurrences', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='UserAltrueAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('altrue_action', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Alt.altrueaction')),
                ('profile_acting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='AltrueLevel',
            fields=[
                ('id', models.IntegerField(auto_created=True, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('minimum_points', models.IntegerField()),
                ('maximum_points', models.IntegerField()),
                ('requiredActions', models.ManyToManyField(blank=True, to='Alt.AltrueAction')),
            ],
        ),
    ]
