# Generated by Django 3.2.7 on 2021-10-26 09:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_link_title'),
        ('Alt', '0051_altrueaction_altruelevel_useraltrueaction'),
    ]

    operations = [
        migrations.CreateModel(
            name='FriendInvite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invited', models.CharField(max_length=50)),
                ('invite_code', models.CharField(max_length=8)),
                ('completed', models.BooleanField(default=False)),
                ('invite_date', models.DateTimeField(auto_now_add=True)),
                ('inviter', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='AltruePointPromotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('altrue_actions', models.ManyToManyField(blank=True, to='Alt.AltrueAction')),
            ],
        ),
    ]
