# Generated by Django 3.2.7 on 2021-10-26 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Alt', '0052_altruepointpromotion_friendinvite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friendinvite',
            name='invite_code',
            field=models.CharField(blank=True, max_length=8),
        ),
    ]
