# Generated by Django 3.2.7 on 2021-10-26 21:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Alt', '0053_alter_friendinvite_invite_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='AltrueActionCode',
            fields=[
                ('id', models.IntegerField(auto_created=True, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='altrueaction',
            name='action_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Alt.altrueactioncode'),
        ),
    ]
