# Generated by Django 3.2.7 on 2021-10-26 21:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Alt', '0054_auto_20211026_2118'),
    ]

    operations = [
        migrations.AddField(
            model_name='friendinvite',
            name='action',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Alt.altrueactioncode'),
            preserve_default=False,
        ),
    ]
