# Generated by Django 3.2.7 on 2021-10-26 22:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_link_title'),
        ('Alt', '0055_friendinvite_action'),
    ]

    operations = [
        migrations.AlterField(
            model_name='altrueaction',
            name='number_of_occurrences',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='altrueaction',
            name='points_awarded',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='altrueactioncode',
            name='code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='altruepointpromotion',
            name='altrue_actions',
            field=models.ManyToManyField(blank=True, null=True, to='Alt.AltrueAction'),
        ),
        migrations.AlterField(
            model_name='friendinvite',
            name='action',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Alt.altrueactioncode'),
        ),
        migrations.AlterField(
            model_name='friendinvite',
            name='invite_code',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='friendinvite',
            name='inviter',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.userprofile'),
        ),
    ]
