# Generated by Django 3.2.7 on 2021-10-26 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Alt', '0056_auto_20211026_2215'),
    ]

    operations = [
        migrations.AddField(
            model_name='altruepointpromotion',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='altruepointpromotion',
            name='multiplier',
            field=models.IntegerField(choices=[(2, 'Double'), (3, 'Triple')], default=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='altruepointpromotion',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='altruepointpromotion',
            name='altrue_actions',
            field=models.ManyToManyField(blank=True, to='Alt.AltrueAction'),
        ),
        migrations.AlterField(
            model_name='nonprofitatrocityrelationship',
            name='projects',
            field=models.ManyToManyField(blank=True, related_name='nonprofitAtrocityRelationship', to='Alt.NonProfitProject'),
        ),
    ]
