# Generated by Django 3.2.7 on 2021-10-27 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Alt', '0057_auto_20211026_2320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='altrueaction',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='altrueactioncode',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='altruelevel',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
