# Generated by Django 3.2.7 on 2021-10-28 05:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Alt', '0059_altruelevel_level_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='altruepointpromotion',
            name='altrue_actions',
        ),
    ]
