# Generated by Django 3.2.7 on 2021-10-28 05:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Alt', '0060_remove_altruepointpromotion_altrue_actions'),
    ]

    operations = [
        migrations.AddField(
            model_name='altrueaction',
            name='is_promoted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='altrueaction',
            name='promotion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Alt.altruepointpromotion'),
        ),
    ]
