# Generated by Django 3.2.7 on 2021-10-29 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Alt', '0061_auto_20211028_0516'),
    ]

    operations = [
        migrations.AddField(
            model_name='altruepointpromotion',
            name='donation_increase',
            field=models.IntegerField(blank=True, choices=[(10, 'Ten Percent'), (20, 'Twenty Percent'), (50, 'Fifty Percent'), (100, 'One Hundred Percent')], null=True),
        ),
        migrations.AlterField(
            model_name='altruepointpromotion',
            name='multiplier',
            field=models.IntegerField(blank=True, choices=[(2, 'Double'), (3, 'Triple')], null=True),
        ),
    ]
