# Generated by Django 3.2.7 on 2021-10-29 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Alt', '0062_auto_20211029_0004'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
