# Generated by Django 3.2.7 on 2021-10-29 23:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0044_alter_altruepoints_last_transaction'),
        ('Alt', '0063_profileimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='profileimage',
            name='profile',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.userprofile'),
        ),
    ]
