# Generated by Django 3.2.7 on 2021-11-21 01:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Alt', '0066_alter_profileimage_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('last_transaction', models.DateTimeField(auto_now=True, null=True)),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Alt.forprofitcompany')),
            ],
        ),
        migrations.RemoveField(
            model_name='nonprofitbalance',
            name='last_transaction',
        ),
        migrations.CreateModel(
            name='CompanyDonation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=6)),
                ('donation_date', models.DateTimeField(auto_now_add=True)),
                ('atrocity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='company_donation_atrocity', to='Alt.atrocity')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_donation', to='Alt.forprofitcompany')),
                ('nonprofit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='company_donation_nonprofit', to='Alt.nonprofit')),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_donation', to='Alt.companybalance')),
            ],
        ),
    ]
