# Generated by Django 3.2.7 on 2022-01-17 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0049_auto_20211121_0117'),
        ('Alt', '0068_alter_nonprofit_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nonprofit',
            name='contributors',
            field=models.ManyToManyField(blank=True, null=True, related_name='contributors', to='api.UserProfile'),
        ),
    ]
