# Generated by Django 3.2.7 on 2022-01-24 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Alt', '0069_alter_nonprofit_contributors'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.CharField(max_length=500),
        ),
    ]
