# Generated by Django 3.2.7 on 2022-01-24 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Alt', '0070_alter_category_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShirtColor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ShirtSize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.IntegerField(choices=[(1, 'XS'), (2, 'S'), (3, 'M'), (4, 'L'), (5, 'XL'), (6, 'XXL')])),
            ],
        ),
        migrations.AddField(
            model_name='shirt',
            name='available_colors',
            field=models.ManyToManyField(blank=True, to='Alt.ShirtColor'),
        ),
        migrations.AddField(
            model_name='shirt',
            name='available_sizes',
            field=models.ManyToManyField(blank=True, to='Alt.ShirtSize'),
        ),
    ]
