# Generated by Django 3.2.7 on 2022-01-24 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Alt', '0071_auto_20220124_1928'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='color',
            field=models.ManyToManyField(related_name='item', to='Alt.ShirtColor'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='size',
            field=models.ManyToManyField(related_name='item', to='Alt.ShirtSize'),
        ),
    ]
