# Generated by Django 3.2.7 on 2022-01-26 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Alt', '0074_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='shirtcolor',
            name='hex_code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
