# Generated by Django 3.2.7 on 2022-01-28 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Alt', '0076_shirtvariations'),
    ]

    operations = [
        migrations.AddField(
            model_name='shirt',
            name='variations',
            field=models.ManyToManyField(to='Alt.ShirtVariations'),
        ),
    ]
