# Generated by Django 3.2.7 on 2022-02-01 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Alt', '0079_auto_20220130_2306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shirtvariations',
            name='image',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
