# Generated by Django 3.2.7 on 2022-02-01 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Alt', '0080_alter_shirtvariations_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forprofitcompany',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='company', to='Alt.Category'),
        ),
    ]
