# Generated by Django 3.2.7 on 2022-02-01 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Alt', '0081_alter_forprofitcompany_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forprofitcompany',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='forprofitcompany',
            name='name',
            field=models.CharField(max_length=30),
        ),
    ]
