# Generated by Django 3.2.7 on 2022-02-01 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Alt', '0082_auto_20220201_1143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forprofitcompany',
            name='year_started',
            field=models.CharField(max_length=4),
        ),
    ]
