# Generated by Django 3.2.7 on 2022-02-17 05:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Alt', '0084_alter_forprofitcompany_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='shirt',
            name='required_level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Alt.altruelevel'),
        ),
    ]
