# Generated by Django 3.2.7 on 2022-02-20 04:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Alt', '0085_shirt_required_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nonprofitproject',
            name='cause',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='np_project_cause', to='Alt.category'),
        ),
        migrations.AlterField(
            model_name='nonprofitproject',
            name='nonprofit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='np_project_nonprofit', to='Alt.nonprofit'),
        ),
    ]
