# Generated by Django 3.2.7 on 2022-03-03 12:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Alt', '0087_companydonation_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyatrocityrelationship',
            name='completed',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='companynonprofitrelationship',
            name='completed',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.CreateModel(
            name='CompanyProjectRelationShip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_level', models.IntegerField(choices=[(10, 'Ten Percent'), (25, 'Twenty Five Percent'), (50, 'Fifty Percent'), (100, 'Full Match')])),
                ('total_raised', models.FloatField(blank=True, default=0, null=True)),
                ('funding_limit', models.FloatField(blank=True, default=0, null=True)),
                ('completed', models.BooleanField(blank=True, default=False)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_match_company', to='Alt.forprofitcompany')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_match', to='Alt.nonprofitproject')),
            ],
        ),
    ]
