# Generated by Django 3.2.7 on 2022-03-03 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Alt', '0088_auto_20220303_1202'),
    ]

    operations = [
        migrations.AddField(
            model_name='nonprofitbalance',
            name='updated_at',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='nonprofitproject',
            name='total_raised',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=9),
        ),
    ]
