# Generated by Django 3.2.7 on 2022-03-05 03:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Alt', '0090_nonprofitproject_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraltrueaction',
            name='date_completed',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
