# Generated by Django 3.2.7 on 2022-03-05 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Alt', '0091_useraltrueaction_date_completed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profileimage',
            name='image',
            field=models.ImageField(default='default.png', upload_to='profiles'),
        ),
    ]
