# Generated by Django 3.2.7 on 2022-03-06 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Alt', '0092_alter_profileimage_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraltrueaction',
            name='is_promotion',
            field=models.BooleanField(default=False),
        ),
    ]
