# Generated by Django 3.2.7 on 2022-03-06 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Alt', '0093_useraltrueaction_is_promotion'),
    ]

    operations = [
        migrations.AddField(
            model_name='altruepointpromotion',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
