# Generated by Django 3.2.7 on 2022-03-06 03:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Alt', '0094_altruepointpromotion_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='altruepointpromotion',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='altruepointpromotion',
            name='start_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
