# Generated by Django 3.2.7 on 2022-03-22 15:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0055_auto_20220303_1449'),
        ('Alt', '0095_auto_20220306_0358'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserMatchRelationShip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('funding_limit', models.FloatField(blank=True, default=0, null=True)),
                ('needs_permission', models.BooleanField(blank=True, default=True)),
                ('match_level', models.IntegerField(choices=[(5, 'Five Percent'), (10, 'Ten Percent'), (25, 'Twenty Five Percent'), (50, 'Fifty Percent'), (100, 'Full Match')])),
                ('user_being_matched', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_being_matched', to='api.userprofile')),
                ('user_matching_donation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_matching', to='api.userprofile')),
            ],
        ),
    ]
