# Generated by Django 3.2.7 on 2022-05-05 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Alt', '0097_usermatchrelationship_was_confirmed'),
    ]

    operations = [
        migrations.AddField(
            model_name='altrueaction',
            name='info',
            field=models.TextField(blank=True, null=True),
        ),
    ]
