# Generated by Django 3.2.7 on 2022-05-20 19:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Alt', '0098_altrueaction_info'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserMatchTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_date', models.DateTimeField(auto_now_add=True)),
                ('total_amount', models.FloatField(blank=True, null=True)),
                ('confirmed', models.BooleanField(default=False)),
                ('relationship', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_match_transaction', to='Alt.usermatchrelationship')),
            ],
        ),
    ]
