# Generated by Django 3.2.4 on 2021-07-09 02:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Alt', '0006_auto_20210630_0744'),
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserDonation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=3)),
                ('donation_type', models.CharField(choices=[('S', 'Single'), ('MU', 'Multiple Orgnanizations')], max_length=2)),
                ('nonprofit', models.ManyToManyField(related_name='user_donation', to='Alt.NonProfit')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_donation', to='api.userprofile')),
                ('wallet', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_donationc', to='api.balance')),
            ],
        ),
    ]
