# Generated by Django 3.2.4 on 2021-07-09 07:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Alt', '0007_auto_20210709_0714'),
        ('api', '0002_userdonation'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdonation',
            name='atrocity',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Alt.atrocity'),
        ),
        migrations.AlterField(
            model_name='userdonation',
            name='nonprofit',
            field=models.ManyToManyField(blank=True, related_name='user_donation', to='Alt.NonProfit'),
        ),
    ]
