# Generated by Django 3.2.4 on 2021-07-09 23:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Alt', '0007_auto_20210709_0714'),
        ('api', '0003_auto_20210709_0714'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdonation',
            name='atrocity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Alt.atrocity'),
        ),
        migrations.AlterField(
            model_name='userdonation',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_donation', to='api.userprofile'),
        ),
        migrations.AlterField(
            model_name='userdonation',
            name='wallet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_donationc', to='api.balance'),
        ),
    ]
