# Generated by Django 3.2.4 on 2021-07-11 04:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Alt', '0009_auto_20210711_0352'),
        ('api', '0004_auto_20210709_2311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdonation',
            name='atrocity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_donation', to='Alt.atrocity'),
        ),
        migrations.RemoveField(
            model_name='userdonation',
            name='nonprofit',
        ),
        migrations.AddField(
            model_name='userdonation',
            name='nonprofit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_donation', to='Alt.nonprofit'),
        ),
    ]
