# Generated by Django 3.2.4 on 2021-07-13 02:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Alt', '0010_auto_20210711_0501'),
        ('api', '0005_auto_20210711_0430'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donor',
            name='donation_category',
        ),
        migrations.AddField(
            model_name='donor',
            name='donation_category',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, related_name='category', to='Alt.category'),
            preserve_default=False,
        ),
    ]
