# Generated by Django 3.2.4 on 2021-07-22 05:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20210713_0221'),
    ]

    operations = [
        migrations.CreateModel(
            name='AltruePoints',
            fields=[
                ('account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='altrue_points', serialize=False, to='api.userprofile')),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
            ],
        ),
    ]
