# Generated by Django 3.2.4 on 2021-09-11 08:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20210807_1554'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='followers',
            field=models.ManyToManyField(blank=True, null=True, related_name='userprofile', to=settings.AUTH_USER_MODEL),
        ),
    ]
