# Generated by Django 3.2.4 on 2021-09-11 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_userprofile_followers'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='followers',
            new_name='following',
        ),
    ]
