# Generated by Django 3.2.4 on 2021-09-18 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Alt', '0022_auto_20210918_0909'),
        ('api', '0010_rename_followers_userprofile_following'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='company_rewards',
            field=models.ManyToManyField(related_name='userprofile', to='Alt.CompanyCoupon'),
        ),
    ]
