# Generated by Django 3.2.4 on 2021-09-19 00:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Alt', '0026_companynonprofitrelationship'),
        ('api', '0011_userprofile_company_rewards'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdonation',
            name='is_matched',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='CompanyMatchDonation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=3)),
                ('atrocity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Alt.atrocity')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Alt.forprofitcompany', verbose_name='')),
                ('nonprofit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='company_donation', to='Alt.nonprofit')),
                ('user_matched', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.userdonation')),
            ],
        ),
    ]
