# Generated by Django 3.2.4 on 2021-09-19 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_auto_20210919_0005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdonation',
            name='is_matched',
            field=models.BooleanField(default=False),
        ),
    ]
