# Generated by Django 3.2.4 on 2021-09-21 00:00

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Alt', '0027_auto_20210919_0005'),
        ('api', '0013_alter_userdonation_is_matched'),
    ]

    operations = [
        migrations.AddField(
            model_name='companymatchdonation',
            name='donation_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='donor',
            name='donation_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userdonation',
            name='donation_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='companymatchdonation',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Alt.forprofitcompany'),
        ),
    ]
