# Generated by Django 3.2.4 on 2021-09-21 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_auto_20210921_0000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donor',
            name='donation_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
