# Generated by Django 3.2.4 on 2021-09-21 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_alter_donor_donation_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='balance',
            name='last_transaction',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
