# Generated by Django 3.2.7 on 2021-09-22 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Alt', '0030_auto_20210921_0801'),
        ('api', '0016_balance_last_transaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='comapnies',
            field=models.ManyToManyField(related_name='userprofile', to='Alt.ForProfitCompany'),
        ),
    ]
