# Generated by Django 3.2.7 on 2021-10-10 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Alt', '0032_rename_owmer_forprofitcompany_owner'),
        ('api', '0018_userprofile_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='comapnies',
            field=models.ManyToManyField(blank=True, related_name='userprofile', to='Alt.ForProfitCompany'),
        ),
    ]
