# Generated by Django 3.2.7 on 2021-10-10 07:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Alt', '0032_rename_owmer_forprofitcompany_owner'),
        ('api', '0019_alter_userprofile_comapnies'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='company_rewards',
            field=models.ManyToManyField(blank=True, related_name='userprofile', to='Alt.CompanyCoupon'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='following',
            field=models.ManyToManyField(blank=True, related_name='userprofile', to=settings.AUTH_USER_MODEL),
        ),
    ]
