# Generated by Django 3.2.7 on 2021-10-15 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_auto_20211010_0733'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='has_company',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='has_nonprofit',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='is_companyContributor',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='is_nonprofitContributor',
            field=models.BooleanField(default=False),
        ),
    ]
