# Generated by Django 3.2.7 on 2021-10-23 02:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Alt', '0044_forprofitcompany_coupons_of_company'),
        ('api', '0022_companynewsupdate'),
    ]

    operations = [
        migrations.CreateModel(
            name='Links',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.CharField(max_length=100)),
                ('author', models.CharField(max_length=30)),
                ('publication', models.CharField(max_length=30)),
                ('atrocity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='link', to='Alt.atrocity')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='link', to='Alt.forprofitcompany')),
                ('nonprofit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='link', to='Alt.nonprofit')),
            ],
        ),
    ]
