# Generated by Django 3.2.7 on 2021-10-23 02:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Alt', '0044_forprofitcompany_coupons_of_company'),
        ('api', '0023_links'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Links',
            new_name='Link',
        ),
    ]
