# Generated by Django 3.2.7 on 2021-10-25 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_alter_link_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='link',
            name='title',
            field=models.CharField(default='The Best Article Ever', max_length=100),
            preserve_default=False,
        ),
    ]
