# Generated by Django 3.2.7 on 2021-10-26 22:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Alt', '0056_auto_20211026_2215'),
        ('api', '0026_link_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companymatchdonation',
            name='user_matched',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.userdonation'),
        ),
        migrations.AlterField(
            model_name='donor',
            name='donation_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='category', to='Alt.category'),
        ),
    ]
