# Generated by Django 3.2.7 on 2021-10-27 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_auto_20211026_2215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='altruepoints',
            name='balance',
            field=models.IntegerField(default=0),
        ),
    ]
