# Generated by Django 3.2.7 on 2021-10-27 06:02

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0031_alter_altruepoints_last_transaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='altruepoints',
            name='last_transaction',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 27, 6, 2, 47, 928137, tzinfo=utc)),
        ),
    ]
