# Generated by Django 3.2.7 on 2021-10-27 06:49

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0032_alter_altruepoints_last_transaction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='qr_code',
        ),
        migrations.AlterField(
            model_name='altruepoints',
            name='last_transaction',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 27, 6, 49, 11, 565821, tzinfo=utc)),
        ),
    ]
