# Generated by Django 3.2.7 on 2021-10-27 06:51

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Alt', '0059_altruelevel_level_number'),
        ('api', '0033_auto_20211027_0649'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='altrue_level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Alt.altruelevel'),
        ),
        migrations.AlterField(
            model_name='altruepoints',
            name='last_transaction',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 27, 6, 50, 59, 724421, tzinfo=utc)),
        ),
    ]
