# Generated by Django 3.2.7 on 2021-10-27 07:06

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0034_auto_20211027_0651'),
    ]

    operations = [
        migrations.AlterField(
            model_name='altruepoints',
            name='last_transaction',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 27, 7, 6, 16, 817704, tzinfo=utc)),
        ),
    ]
