# Generated by Django 3.2.7 on 2021-10-27 07:13

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Alt', '0059_altruelevel_level_number'),
        ('api', '0035_alter_altruepoints_last_transaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='requirementsForNextLevel',
            field=models.ManyToManyField(blank=True, related_name='userprofile', to='Alt.UserAltrueAction'),
        ),
        migrations.AlterField(
            model_name='altruepoints',
            name='last_transaction',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 27, 7, 13, 36, 430519, tzinfo=utc)),
        ),
    ]
