# Generated by Django 3.2.7 on 2021-10-28 05:09

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0038_auto_20211027_0851'),
    ]

    operations = [
        migrations.AlterField(
            model_name='altruepoints',
            name='last_transaction',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 28, 5, 9, 52, 831737, tzinfo=utc)),
        ),
    ]
