# Generated by Django 3.2.7 on 2021-10-28 05:16

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0039_alter_altruepoints_last_transaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='altruepoints',
            name='last_transaction',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 28, 5, 16, 46, 363709, tzinfo=utc)),
        ),
    ]
