# Generated by Django 3.2.7 on 2021-10-29 23:09

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0046_auto_20211029_2305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='altruepoints',
            name='last_transaction',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 29, 23, 9, 25, 211865, tzinfo=utc)),
        ),
    ]
