# Generated by Django 3.2.7 on 2022-02-16 01:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Alt', '0084_alter_forprofitcompany_logo'),
        ('api', '0049_auto_20211121_0117'),
    ]

    operations = [
        migrations.CreateModel(
            name='NonProfitRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_message', models.TextField(blank=True, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='request', to='Alt.forprofitcompany')),
                ('nonprofit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='request', to='Alt.nonprofit')),
            ],
        ),
        migrations.CreateModel(
            name='RequestVotes',
            fields=[
                ('id', models.IntegerField(auto_created=True, editable=False, primary_key=True, serialize=False)),
                ('message', models.TextField(blank=True, null=True)),
                ('np_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voter', to='api.nonprofitrequest')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voter', to='api.userprofile')),
            ],
        ),
    ]
