# Generated by Django 3.2.7 on 2022-02-26 00:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Alt', '0086_auto_20220220_0443'),
        ('api', '0051_userprofile_profiles_following'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdonation',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_donation', to='Alt.nonprofitproject'),
        ),
    ]
