# Generated by Django 3.2.7 on 2022-03-03 03:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Alt', '0087_companydonation_project'),
        ('api', '0052_userdonation_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='companymatchdonation',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='company_match_donation', to='Alt.nonprofitproject'),
        ),
        migrations.AlterField(
            model_name='companymatchdonation',
            name='nonprofit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='company_match_donation', to='Alt.nonprofit'),
        ),
    ]
