# Generated by Django 3.2.7 on 2022-03-03 12:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0053_auto_20220303_0341'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companymatchdonation',
            name='user_matched',
        ),
        migrations.AddField(
            model_name='companymatchdonation',
            name='transaction_matched',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='company_match_donation', to='api.userdonation'),
        ),
    ]
